name: Build and Deploy Android App

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Decode keystore file
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > app/release.keystore
         
    - name: Build and Sign AAB
      run: ./gradlew :app:assembleRelease --stacktrace
      env:
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

    - name: List output files
      run: ls -R app/build/outputs/bundle/release/

    - name: Upload to Google Play
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_SERVICE_ACCOUNT_JSON }}
        packageName: com.akaiyukiusagi.quicktodo
        releaseFiles: app/build/outputs/bundle/release/app-release.aab
        track: production
