name: Build and Deploy Android App

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Decode keystore file
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > app/release.keystore

    - name: Build and Sign AAB
      run: ./gradlew :app:bundleRelease --stacktrace
      env:
        KEYSTORE_ALIAS: "test"
        KEYSTORE_ALIAS_PASSWORD: "test"
        KEYSTORE_STORE_PASSWORD: "test"

    - name: Upload to Google Play
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_SERVICE_ACCOUNT_JSON }}
        packageName: com.akaiyukiusagi.quicktodo
        releaseFile: app/build/outputs/bundle/release/app-release.aab
        track: production
