name: Build and Deploy Android App

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'  # Adoptium (以前のAdoptOpenJDK) のビルドを使用

    - name: Decode keystore file
      run: |
        echo "${{ secrets.KEYSTORE }}" | base64 -d > release.keystore

    - name: Build and Sign AAB
      run: |
        echo "${{ secrets.KEYSTORE }}" | base64 -d > release.keystore
        ./gradlew bundleRelease -Pandroid.injected.signing.store.file=release.keystore -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

    - name: Upload to Google Play
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_SERVICE_ACCOUNT_JSON }}
        packageName: com.akaiyukiusagi.quicktodo
        releaseFile: app/build/outputs/bundle/release/app-release.aab
        track: production
